name: Create Release and Update Repository

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    uses: welldooder64/DalamudPluginRepo/.github/workflows/create-release.template.yml@main
    with:
      internal-name: WebMap
      build-location: WebMap.Plugin/bin/x64/Release
      personal-plugin-repo: welldooder64/DalamudPluginRepo
      personal-plugin-repo-branch: main
    secrets: inherit
