name: Create Release and Update Repository

on:
    push:
        tags:
            - 'v*'

permissions:
    contents: write

jobs:
    release:
        uses: welldooder64/DalamudPluginRepo/.github/workflows/create-release.template.yml@main
        with:
            internal_name: WebMap
            solution_name: WebMap
            build_configuration: Release
            personal_plugin_repo: welldooder64/DalamudPluginRepo
            personal_plugin_repo_branch: main
        secrets: inherit
